__include__: [
  'dataset/coco_detection.yml',
  '../rtdetr/include/dataloader.yml',
]

model: PResNet

PResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True